Set up pods
otus-kuber-2020-11/VladimirTambovtsev_platform pull request #2
Opened 2020-12-06 23:15 UTC by VladimirTambovtsev

# Выполнено ДЗ №

- [x] Основное ДЗ
- [x] Задание со \*

## В процессе сделано:

- Добавлен Node.js сервер на порту 8080
- Отправлен образ `microservices-demo frontend` на dockerhub и исправлен в файле `frontend-pod-healty.yaml`
- Проверены поды и настроен Kube Forwarder

## Как запустить проект:

- `kubectl apply -f web-pod.yaml`
- `kubectl apply -f frontend-pod-healthy.yaml`

## Как проверить работоспособность:

- `kubectl port-forward --address 0.0.0.0 pod/k8s-app-node-server 8000:8000`
- `kubectl port-forward --address 0.0.0.0 pod/frontend 8080:8080`

Или через Kube Forwarder

## PR checklist:

- [x] Выставлен label с темой домашнего задания

2020-12-06 23:32 UTC, VladimirTambovtsev commented
Добрый день. Не проходят тесты, с чем связано?

<img width="1096" alt="Снимок экрана 2020-12-07 в 02 31 47" src="https://user-images.githubusercontent.com/25567610/101296402-5d515c00-3834-11eb-90bf-7ebf85606a18.png">

2020-12-07 18:29 UTC, Jasstkn requested changes
Добрый день.
Для принятия домашнего задания необходимо добиться зеленых тестов :)

2020-12-07 18:29 UTC, Jasstkn commented on kubernetes-intro/web-pod.yaml
> +  name: k8s-app-node-server # Название Pod
У вас свалились тесты, попробуйте переименовать под на `web`

2020-12-07 21:14 UTC, VladimirTambovtsev commented on kubernetes-intro/web-pod.yaml
> +  name: k8s-app-node-server # Название Pod
Исправил, спасибо
Но сейчас то что?)

<img width="1089" alt="Снимок экрана 2020-12-08 в 00 12 15" src="https://user-images.githubusercontent.com/25567610/101406235-39e8e880-38ea-11eb-80ff-f920c7e3bc0b.png">

<img width="604" alt="Снимок экрана 2020-12-08 в 00 13 24" src="https://user-images.githubusercontent.com/25567610/101406207-32294400-38ea-11eb-926f-bd99927feb43.png">

2020-12-14 19:25 UTC, Jasstkn approved these changes
Добрый день. Все сделано верно - аппрув!

2020-12-14 19:25 UTC, Jasstkn commented
Если интересно почитайте про resources и securityContext:
- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
- https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

2020-12-14 19:25 UTC, merged

2020-12-26 11:26 UTC, VladimirTambovtsev commented
Спасибо, отлично!